#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

#include "../lib/sha3.h"

static const char *selected_files[] = {
    "lib/KCMVP_Crypto.c",
    "lib/module_state.c",
    "lib/selftest.c",
    "lib/integrity.c",
    "lib/entropy.c",
    "lib/hash_drbg.c",
    "lib/ecc.c",
    "third_party/micro-ecc/uECC.c",
    "lib/mlkem.c",
    "lib/mlkem_randombytes.c",
    "third_party/PQClean/common/fips202.c",
    "third_party/PQClean/crypto_kem/ml-kem-768/clean/cbd.c",
    "third_party/PQClean/crypto_kem/ml-kem-768/clean/indcpa.c",
    "third_party/PQClean/crypto_kem/ml-kem-768/clean/kem.c",
    "third_party/PQClean/crypto_kem/ml-kem-768/clean/ntt.c",
    "third_party/PQClean/crypto_kem/ml-kem-768/clean/poly.c",
    "third_party/PQClean/crypto_kem/ml-kem-768/clean/polyvec.c",
    "third_party/PQClean/crypto_kem/ml-kem-768/clean/reduce.c",
    "third_party/PQClean/crypto_kem/ml-kem-768/clean/symmetric-shake.c",
    "third_party/PQClean/crypto_kem/ml-kem-768/clean/verify.c",
    "lib/aria.c",
    "lib/aria.h",
    "lib/aria_Mode.c",
    "lib/sha3.c",
    "lib/KISA_HMAC_SHA3.c"
};

static int hash_file(const char *path, uint8_t digest[32])
{
    uint8_t buffer[4096];
    FILE *file = fopen(path, "rb");
    size_t bytes_read;
    SHA3_CTX sha3_ctx;

    if (file == NULL)
        return -1;

    if (sha3_init(&sha3_ctx, 256, SHA3_SHAKE_NONE) != 0) {
        fclose(file);
        return -1;
    }
    while ((bytes_read = fread(buffer, 1, sizeof(buffer), file)) > 0) {
        if (sha3_update(&sha3_ctx, buffer, (int)bytes_read) != 0) {
            fclose(file);
            return -1;
        }
    }
    if (ferror(file) || sha3_final(&sha3_ctx, digest, 32) != 0) {
        fclose(file);
        return -1;
    }

    fclose(file);
    return 0;
}

int main(int argc, char **argv)
{
    uint8_t digest[32];
    size_t file_count = sizeof(selected_files) / sizeof(selected_files[0]);
    size_t i;
    size_t j;
    FILE *output;

    if (argc != 2) {
        fprintf(stderr, "usage: %s OUTPUT\n", argv[0]);
        return 1;
    }

    output = fopen(argv[1], "w");
    if (output == NULL) {
        perror(argv[1]);
        return 1;
    }

    fprintf(output, "/* Generated by tools/generate_integrity_manifest.c. */\n");
    fprintf(output, "#ifndef KCMVP_INTEGRITY_MANIFEST_H\n");
    fprintf(output, "#define KCMVP_INTEGRITY_MANIFEST_H\n\n");
    fprintf(output, "#define KCMVP_INTEGRITY_FILE_COUNT %zu\n\n", file_count);
    fprintf(output, "static const KCMVP_INTEGRITY_ENTRY ");
    fprintf(output, "kcmvp_integrity_manifest[KCMVP_INTEGRITY_FILE_COUNT] = {\n");

    for (i = 0; i < file_count; i++) {
        if (hash_file(selected_files[i], digest) != 0) {
            fprintf(stderr, "cannot hash %s\n", selected_files[i]);
            fclose(output);
            return 1;
        }

        fprintf(output, "    { \"%s\", {", selected_files[i]);
        for (j = 0; j < sizeof(digest); j++)
            fprintf(output, "%s0x%02x", j == 0 ? " " : ", ", digest[j]);
        fprintf(output, " } },\n");
    }

    fprintf(output, "};\n\n#endif\n");
    if (fclose(output) != 0)
        return 1;
    return 0;
}
